name: CI Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: ['17']

    steps:
    - uses: actions/checkout@v4 
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Run Build and Logic Tests with Maven
      run: mvn clean test-compile

    - name: Run Snyk Security Scan
      if: matrix.os == 'ubuntu-latest'
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        JAVA_HOME: /opt/java/openjdk
      with:
        args: --severity-threshold=high